### ISSUE TITLE
Hide "Eliminate Layout Shift" pseudo-element non-visually

### ISSUE THREAD

**Issue by extra808** [zachleat/heading-anchors#2]
This styling that's applied before the custom element is defined (and stays if the JavaScript doesn't run) visually hides the pseudo-element but the `content` remains and becomes a part of the heading. To a screen reader, "Heading 2" becomes "Heading 2#" (in my configuration, VoiceOver says "Heading 2 pound").

```CSS
heading-anchors:not(:defined) :is(h2,h3,h4,h5,h6):after {
	content: "#";
	padding: 0 .25em;
	opacity: 0;
}
```

Including [alternative text in `content`](https://caniuse.com/mdn-css_properties_content_alt_text) is now supported in current versions of major browsers and can be used to treat the content as decorative: `content: "#" / "";`.

This version of the rule has the original `content` as a fallback for older browsers. It also includes `[id]` in the selector since only headings with ids get anchors.

```CSS
heading-anchors:not(:defined) :is(h2,h3,h4,h5,h6)[id]::after {
	content: "#";
	content: "#" / "";
	padding: 0 .25em;
	opacity: 0;
}
```
